# Base configs
baseurl: "https://qiaopengju.github.io/photography/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Pengju Qiao"
subtitle: "See the world through my eyes!"
author: "Pengju Qiao"
header:
 title: "Photography"
 subtitle: "by 樵鹏举"
footer:
 name: "Hey there, my name is Pengju Qiao"
 bio: "我是中国科学院大学软件所图形学方向研究生；研究方向为计算机图形学，深度学习；兴趣爱好是绘画、羽毛球。"
#  github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  # twitter: "https://www.twitter.com/ram__patra"
  # instagram: "https://www.instagram.com/ram_patra"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/qiaopengju"
